-- Enable Row Level Security (RLS) on all public tables for Supabase Security Advisor.
-- Backend uses role postgres (superuser), so RLS is bypassed and app keeps working.

ALTER TABLE "Tenant" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Client" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ClientContact" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ClientUser" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Ticket" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TicketResponsible" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProjectResponsible" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Project" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Activity" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TimeEntry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TicketComment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TicketHistory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TicketCommentAttachment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TicketAttachment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TimeEntryPermissionRequest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HourBankRecord" ENABLE ROW LEVEL SECURITY;

-- User table (table name in DB is "users")
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;
